package workshop2;

import java.text.MessageFormat;

/**
 * @author ChangSiiang This is a person class. This will be the base on which to
 *         build the club members class. Give the Person class three attributes:
 *         surname, first name and second name. Make these attributes private.
 * 
 *         Add a constructor that will accept the initialisation values for
 *         these three attributes.
 * 
 *         In the ClubApplication class's main() method, declare and instantiate
 *         a Person object. Use arbitrary test values for the names. Make sure
 *         the system still compiles and runs. Verify that Person.class is
 *         present in your directory.
 * 
 *         Make the second name attribute optional for class Person. In other
 *         words Allow the Person class to be instantiated when a null value is
 *         passed for the second name. This would allow both "Tan Ah Beng" and
 *         "Stan Laurel" to be valid names. Make sure the show methods handles
 *         this correctly.
 *
 */

public class Person {

	private String surName;
	private String firstName;
	private String secondName;

	/*
	 * This constructor is generated by Eclipse by, Step 1) Create the attributes
	 * Step 2) Right click on code window, select "Source",
	 * "Generate Constructor Using Field" Step 3) Select the attributes for the
	 * constructor and click "OK"
	 */
	public Person(String surName, String firstName, String secondName) {
		this.surName = surName;
		this.firstName = firstName;
		this.secondName = secondName;
	}

	/*
	 * These getters are generated using Eclipse by the following steps: Step 1)
	 * Create the attributes Step 2) Right click on the code window, select "Source"
	 * > "Generate Getters and Setters Step 3) Select the attributes (by default,
	 * both get and set will be created) Step 4) Expand the attribute branch to
	 * exclude the setters Step 5) Select the appropriate visibility and click "OK"
	 * "
	 */

	public String getSurName() {
		return surName;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getSecondName() {
		return secondName;
	}

	/*
	 * show() method to print the attributes This is written by hand
	 */

	public void show() {

		System.out.println(this.toString());
	}

	/* Override the toString() so that it will return the full name of the person */

	@Override
	public String toString() {
		if (this.secondName == null) {
			return MessageFormat.format("{0} {1}", surName, firstName);
		} else {
			return MessageFormat.format("{0} {1} {2}", surName, firstName, secondName);
		}
	}

}
